### PR TITLE
17 make all image placeholders dynamic

### PR DESCRIPTION
**Pull request by Kolozuz**
# Change Details 

Added dynamic placeholder images, using [Dicebear](https://www.dicebear.com) and [Picsum](https://picsum.photos/) (was already in use on other placeholder imgs)

Dicebear styles used
[Initials](https://www.dicebear.com/styles/initials/)
[Notionists](https://www.dicebear.com/styles/notionists/)

## Issues or Fixes 

#17 

## Before merging branches 

- [x] Reviewed by one or more developers on the team.
- [x] Tests.

### CODE REVIEW

**Review by JohnGolgota — CHANGES_REQUESTED** [review]
la 🐤 las utilitis
PERO
PORQUE IJUEPUTA HAY .ts FUERA DE SRC?! LOCO?! PERO QUE MONDA?!

**Comment by Kolozuz** [comment]
> la 🐤 las utilitis PERO PORQUE IJUEPUTA HAY .ts FUERA DE SRC?! LOCO?! PERO QUE MONDA?!

Ah jajjaja ya lo andaba haciendo como mvc de php

**Review by Kolozuz — COMMENTED** [review]
@JohnGolgota changes done

**Review by Kolozuz — COMMENTED** [review]
No se que estoy haciendo

**Review by JohnGolgota — APPROVED** [review]
# 👍

**Comment by JohnGolgota** [comment]
Sin miedo.

**Pull request merged**
